[package]
name = "mytest"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
lazy_static = "1.4"
parking_lot = "0.11"
dashmap = "4.0"
num = "0.2.1"
